databases:
  - name: fibonacci_api_db
    region: singapore
    plan: free
    databaseName: fibonacci_api_db
    user: guro

services:
  - type: web
    name: fibonacci_api
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn fibonacci_api.asgi:application -k uvicorn.workers.UvicornWorker'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fibonacci_api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4